/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  basicSidebar: [
    {
      type: 'category',
      label: '基础算法',
      link: { type: 'doc', id: 'basic' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'basic',
        }
      ]
    }
  ],
  algebraSidebar: [
    {
      type: 'category',
      label: '代数',
      link: { type: 'doc', id: 'algebra' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'algebra',
        }
      ]
    }
  ],
  dataStructureSidebar: [
    {
      type: 'category',
      label: '基础数据结构',
      link: { type: 'doc', id: 'data-structure' },
      items: ['data-structure/stack/README', 'data-structure/queue/README'],
    },
    {
      type: 'category',
      label: '进阶数据结构',
      items: ['data-structure/balanced-binary-search-tree/README', 'data-structure/disjoint-sets-union/README', 'data-structure/segment-tree/README']
    }
  ],
  graphSidebar: [{
    type: 'category',
    label: '图论',
    link: { type: 'doc', id: 'graph' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'graph',
      }
    ]
  }],
  dpSidebar: [{
    type: 'category',
    label: '动态规划',
    link: { type: 'doc', id: 'dp' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'dp',
      }
    ]
  }],
  geometrySidebar: [{
    type: 'category',
    label: '计算几何',
    link: { type: 'doc', id: 'geometry' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'geometry',
      }
    ]
  }],
  stringSidebar: [{
    type: 'category',
    label: '字符串',
    link: { type: 'doc', id: 'string' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'string',
      }
    ]
  }]
};

module.exports = sidebars;
